// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsEFAssignment.Contexts;

namespace EFCoreAssignment.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20201111094608_AddRandomSeedData")]
    partial class AddRandomSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("StudentsEFAssignment.Entities.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Data",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 2L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 3L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Tutashkhia"
                        },
                        new
                        {
                            Id = 4L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Montoya"
                        },
                        new
                        {
                            Id = 5L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 6L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Montoya"
                        },
                        new
                        {
                            Id = 7L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 8L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 9L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 10L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 11L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 12L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Data",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 13L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 14L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 15L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 16L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Data",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 17L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Tutashkhia"
                        },
                        new
                        {
                            Id = 18L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 19L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Montoya"
                        },
                        new
                        {
                            Id = 20L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Montoya"
                        },
                        new
                        {
                            Id = 21L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 22L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Data",
                            LastName = "Tutashkhia"
                        },
                        new
                        {
                            Id = 23L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 24L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 25L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 26L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 27L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Montoya"
                        },
                        new
                        {
                            Id = 28L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 29L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Montoya"
                        },
                        new
                        {
                            Id = 30L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 31L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Data",
                            LastName = "Montoya"
                        },
                        new
                        {
                            Id = 32L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Montoya"
                        },
                        new
                        {
                            Id = 33L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 34L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 35L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 36L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Data",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 37L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Joe",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 38L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            LastName = "Montoya"
                        },
                        new
                        {
                            Id = 39L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 40L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Data",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 41L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 42L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Tutashkhia"
                        },
                        new
                        {
                            Id = 43L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 44L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Data",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 45L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 46L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 47L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Data",
                            LastName = "Tutashkhia"
                        },
                        new
                        {
                            Id = 48L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Inigo",
                            LastName = "Kufaradze"
                        },
                        new
                        {
                            Id = 49L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Data",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 50L,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mzia",
                            LastName = "Kufaradze"
                        });
                });

            modelBuilder.Entity("StudentsEFAssignment.Entities.StudentSubject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentSubjects");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            StudentId = 1L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            StudentId = 1L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            StudentId = 2L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            StudentId = 2L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            StudentId = 3L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            StudentId = 3L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            StudentId = 4L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 8L,
                            StudentId = 4L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            StudentId = 5L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 10L,
                            StudentId = 5L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 11L,
                            StudentId = 6L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 12L,
                            StudentId = 6L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 13L,
                            StudentId = 7L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 14L,
                            StudentId = 7L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            StudentId = 8L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            StudentId = 8L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            StudentId = 9L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 18L,
                            StudentId = 9L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 19L,
                            StudentId = 10L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 20L,
                            StudentId = 10L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 21L,
                            StudentId = 11L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 22L,
                            StudentId = 11L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 23L,
                            StudentId = 12L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 24L,
                            StudentId = 12L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 25L,
                            StudentId = 13L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 26L,
                            StudentId = 13L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 27L,
                            StudentId = 14L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 28L,
                            StudentId = 14L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 29L,
                            StudentId = 15L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 30L,
                            StudentId = 15L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 31L,
                            StudentId = 16L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 32L,
                            StudentId = 16L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 33L,
                            StudentId = 17L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 34L,
                            StudentId = 17L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 35L,
                            StudentId = 18L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 36L,
                            StudentId = 18L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 37L,
                            StudentId = 19L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 38L,
                            StudentId = 19L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 39L,
                            StudentId = 20L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 40L,
                            StudentId = 20L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 41L,
                            StudentId = 21L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 42L,
                            StudentId = 21L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 43L,
                            StudentId = 22L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 44L,
                            StudentId = 22L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 45L,
                            StudentId = 23L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 46L,
                            StudentId = 23L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 47L,
                            StudentId = 24L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 48L,
                            StudentId = 24L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 49L,
                            StudentId = 25L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 50L,
                            StudentId = 25L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 51L,
                            StudentId = 26L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 52L,
                            StudentId = 26L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 53L,
                            StudentId = 27L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 54L,
                            StudentId = 27L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 55L,
                            StudentId = 28L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 56L,
                            StudentId = 28L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 57L,
                            StudentId = 29L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 58L,
                            StudentId = 29L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 59L,
                            StudentId = 30L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 60L,
                            StudentId = 30L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 61L,
                            StudentId = 31L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 62L,
                            StudentId = 31L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 63L,
                            StudentId = 32L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 64L,
                            StudentId = 32L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 65L,
                            StudentId = 33L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 66L,
                            StudentId = 33L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 67L,
                            StudentId = 34L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 68L,
                            StudentId = 34L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 69L,
                            StudentId = 35L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 70L,
                            StudentId = 35L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 71L,
                            StudentId = 36L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 72L,
                            StudentId = 36L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 73L,
                            StudentId = 37L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 74L,
                            StudentId = 37L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 75L,
                            StudentId = 38L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 76L,
                            StudentId = 38L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 77L,
                            StudentId = 39L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 78L,
                            StudentId = 39L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 79L,
                            StudentId = 40L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 80L,
                            StudentId = 40L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 81L,
                            StudentId = 41L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 82L,
                            StudentId = 41L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 83L,
                            StudentId = 42L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 84L,
                            StudentId = 42L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 85L,
                            StudentId = 43L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 86L,
                            StudentId = 43L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 87L,
                            StudentId = 44L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 88L,
                            StudentId = 44L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 89L,
                            StudentId = 45L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 90L,
                            StudentId = 45L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 91L,
                            StudentId = 46L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 92L,
                            StudentId = 46L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 93L,
                            StudentId = 47L,
                            SubjectId = 5L
                        },
                        new
                        {
                            Id = 94L,
                            StudentId = 47L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 95L,
                            StudentId = 48L,
                            SubjectId = 4L
                        },
                        new
                        {
                            Id = 96L,
                            StudentId = 48L,
                            SubjectId = 3L
                        },
                        new
                        {
                            Id = 97L,
                            StudentId = 49L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 98L,
                            StudentId = 49L,
                            SubjectId = 2L
                        },
                        new
                        {
                            Id = 99L,
                            StudentId = 50L,
                            SubjectId = 1L
                        },
                        new
                        {
                            Id = 100L,
                            StudentId = 50L,
                            SubjectId = 2L
                        });
                });

            modelBuilder.Entity("StudentsEFAssignment.Entities.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "MATH-301",
                            Credits = 5,
                            Name = "Differential Equations"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "CS-215",
                            Credits = 6,
                            Name = "Object Oriented Programming"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "CS-930",
                            Credits = 7,
                            Name = "Computer Networks"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "CS-592",
                            Credits = 5,
                            Name = "Game Development"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "PHY-101",
                            Credits = 6,
                            Name = "Physics"
                        });
                });

            modelBuilder.Entity("StudentsEFAssignment.Entities.StudentSubject", b =>
                {
                    b.HasOne("StudentsEFAssignment.Entities.Student", null)
                        .WithMany("Subjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentsEFAssignment.Entities.Subject", null)
                        .WithMany("students")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentsEFAssignment.Entities.Student", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("StudentsEFAssignment.Entities.Subject", b =>
                {
                    b.Navigation("students");
                });
#pragma warning restore 612, 618
        }
    }
}
